name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Install abseil
        run: brew install abseil

      - name: Build & test
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DCPPBENCH_WITH_ABSEIL=ON ..
          cmake --build . -j 2
          ctest
          ./bench/bench4

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build & test
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -j 2
          ctest
          ./bench/bench4

  coverage-test:
    name: Coverage Testing
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: pip install gcovr

      - name: Build & test
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" ..
          cmake --build . -j 2
          ctest

      - name: Generate coverage report
        run: |
          gcovr -r . -f src/ --xml -o coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          verbose: true
